version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rate_limiter_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rate_limiter
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rate_limiter"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: rate_limiter_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DL=postgresql://postgres:password@db:5432/rate_limiter?schema=public
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma db push && npm start"

volumes:
  pgdata:
